project:
  title: "Dissertacao_edson"

number-sections: true

bibliography: "references.bib"
csl: "./src/abnt2.csl"

#lembrar - aqui eu configurei chapter como section, então, atenção
format:
  pdf:
    toc: false
    pdf-engine: xelatex
    include-in-header: "./src/preamble.tex"
    documentclass:
      "abntex2"
    classoption:
      - "12pt"
      - "oneside"
      - "a4paper"
      - "chapter=TITLE"
      - "section=title"
      - "sumario=abnt-6027-2012"
      - "brazilian"
    geometry:
      - top=30mm
      - left=30mm
      - right=20mm
      - bottom=20mm
    include-before-body: []
    babel-options: brazilian
    colorlinks: false
    linkcolor: black
    urlcolor: black
    citecolor: black
    code-block-bg: true
    code-block-border-left: true
    highlight-style: github
    keep-tex: true

link-citations: true

fig-cap-location: top

execute:
  echo: false
  warning: false
  freeze: auto

# knitr:
#   opts_chunk:
#     out.width: "100%"

# https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language-pt-BR.yml
# dicionário para o Quarto, entrada separada por conta do conflito com bib Bable (LaTeX)

crossref:
  fig-title: "**Figura**"
  fig-prefix : "Figura"
  tbl-title: "**Tabela**"
  tbl-prefix : "Tabela"
  lst-title: "Listagem"
  thm-title: "**Teorema**"
  lem-title: "Lema"
  cor-title: "Corolário"
  prp-title: "Proposição"
  cnj-title: "Conjectura"
  def-title: "Definição"
  exm-title: "Exemplo"
  exr-title: "Exercício"
  sec-prefix: "seção"
  eq-prefix: "equação"
  lof-title: "LISTA DE FIGURAS"
  lot-title: "LISTA DE TABELAS"
  lol-title: "LISTA DE LISTAGENS"
